### ISSUE TITLE
RecyclerView support

### ISSUE THREAD

**Issue by max02100** [felipecsl/AsymmetricGridView#49] opened 2015-10-14 08:31 UTC
Hello, i saw that the version 2 support the recycler view but there is no example. 

Someone has this please? 

Thanks

**Comment by felipecsl** [comment] 2015-10-14 16:20
RecyclerView support hasn't been implemented yet. I'm still working on it.
Closing as a duplicate of #26

**Closed by felipecsl** 2015-10-14 16:20 UTC
