### ISSUE TITLE
    java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. [in ListView(2131428879, AsymmetricGridView) with Adapter(class AsymmetricGridViewAdapter)]    

### ISSUE THREAD

**Issue by rainbowr55** [felipecsl/AsymmetricGridView#32] opened 2015-06-11 10:08 UTC
my listview data is often changed , sometime the error will be happen

**Comment by hopesenddreams** [comment] 2015-08-08 20:17
probably not a bug. You should post your Adapter because that's most likely where the issue is. You have to be very careful because of the nested Adapter structure. Look at ArrayAdapter https://github.com/android/platform_frameworks_base/blob/master/core/java/android/widget/ArrayAdapter.java for ideas.

**Comment by felipecsl** [comment] 2015-08-11 01:53
closing until more information is provided

**Closed by felipecsl** 2015-08-11 01:53 UTC
